version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile      
    ports:
      - 8080:8080
    volumes:
      - .:/target
    depends_on:
      - db
      - elasticsearch
  db:
    image: mysql:5.7.37
    container_name: jobportal_mysql
    restart: always
    environment:
      MYSQL_DATABASE: job_portal
      MYSQL_USER: sunny
      MYSQL_PASSWORD: sunny
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601